"""Assembler — assembles final outputs from pipeline stages.

Assembles:
- script.yaml (complete script from all chapter YAML files)
- Chapter summaries (100-char per chapter, generated by ContinuityCompressor)
- Continuity summary compression (delegated to ContinuityCompressor)
- Final output to workspace/90_output/
"""

import json
from typing import Optional

import yaml

from app.pipeline.continuity_compressor import ContinuityCompressor
from app.schemas import Script, MetaInfo, Episode, Scene, Beat, Dialogue, ContinuityRecord, ContinuitySummary
from app.workspace import workspace_manager


class Assembler:
    """Assemble final outputs from pipeline stages."""

    def __init__(self, project_id: str):
        self.project_id = project_id
        self.compressor = ContinuityCompressor(project_id)

    def execute(self, novel_title: str = "") -> Script:
        """Assemble the complete script from chapter YAML files.

        Returns the assembled Script object and writes it to workspace/90_output/.
        Also generates chapter summaries and compresses continuity.
        """
        # Read all chapter YAML files
        scripts = workspace_manager.list_files(self.project_id, "40_scripts")
        yaml_files = sorted([f for f in scripts if f.endswith(".yaml")])

        episodes = []
        for yaml_file in yaml_files:
            content = workspace_manager.read_file(self.project_id, "40_scripts", yaml_file)
            try:
                episode = self._parse_episode_yaml(content)
                if episode:
                    episodes.append(episode)
            except Exception:
                continue

        # Read analysis for metadata
        genre = ""
        main_characters = ""
        try:
            analysis_data = workspace_manager.read_json(
                self.project_id, "20_analysis", "analysis.json"
            )
            genre = analysis_data.get("genre", "")
            # Extract main character names from analysis
            chars = analysis_data.get("characters", [])
            if chars:
                protagonist = next((c for c in chars if c.get("role") == "protagonist"), None)
                if protagonist:
                    main_characters = protagonist.get("name", "")
        except Exception:
            pass

        # Try to get novel title from raw file or project info
        source_novel = novel_title
        if not source_novel:
            # Try reading first line of novel as title candidate
            try:
                raw_text = workspace_manager.read_file(self.project_id, "00_raw", "novel.txt")
                first_line = raw_text.strip().split("\n")[0].strip()
                if first_line and len(first_line) < 50:
                    source_novel = first_line
            except Exception:
                pass

        # Build complete script
        script = Script(
            meta=MetaInfo(
                title=novel_title or source_novel or "未命名剧本",
                genre=genre,
                source_novel=source_novel or novel_title or "",
                total_episodes=len(episodes),
                version="1.1",
            ),
            episodes=episodes,
        )

        # Write final script.yaml
        script_yaml = yaml.dump(
            script.model_dump(),
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
        )
        workspace_manager.write_file(
            self.project_id, "90_output", "script.yaml", script_yaml
        )

        # A5: Generate chapter summaries using ContinuityCompressor
        self._generate_chapter_summaries(yaml_files)

        # Delegate continuity compression to ContinuityCompressor (C1)
        self.compressor.compress()

        return script

    def _parse_episode_yaml(self, yaml_content: str) -> Optional[Episode]:
        """Parse a single episode YAML file into an Episode model."""
        try:
            data = yaml.safe_load(yaml_content)
            if not isinstance(data, dict):
                return None

            # Parse scenes
            scenes = []
            for scene_data in data.get("scenes", []):
                beats = []
                for beat_data in scene_data.get("beats", []):
                    dialogues = []
                    for dlg_data in beat_data.get("dialogues", []):
                        dialogues.append(Dialogue(
                            character=dlg_data.get("character", ""),
                            line=dlg_data.get("line", ""),
                            direction=dlg_data.get("direction", ""),
                        ))
                    beats.append(Beat(
                        beat_phase=beat_data.get("beat_phase"),
                        description=beat_data.get("description", ""),
                        dialogues=dialogues,
                        emotion_marker=beat_data.get("emotion_marker"),
                        conflict_type=beat_data.get("conflict_type"),
                    ))
                scenes.append(Scene(
                    scene_number=scene_data.get("scene_number", 0),
                    location=scene_data.get("location", ""),
                    time_of_day=scene_data.get("time_of_day", ""),
                    beats=beats,
                    is_paywall=scene_data.get("is_paywall"),
                ))

            return Episode(
                episode_number=data.get("episode_number", 0),
                title=data.get("title", ""),
                logline=data.get("logline", ""),
                scenes=scenes,
            )
        except Exception:
            return None

    def _generate_chapter_summaries(self, yaml_files: list[str]) -> None:
        """A5: Generate 100-char summaries for each chapter.

        Uses ContinuityCompressor.generate_chapter_summary().
        """
        for yaml_file in yaml_files:
            content = workspace_manager.read_file(self.project_id, "40_scripts", yaml_file)
            # Extract episode number from filename like chapter_01.yaml
            try:
                ep_num = int(yaml_file.replace("chapter_", "").replace(".yaml", ""))
            except ValueError:
                continue

            summary_data = self.compressor.generate_chapter_summary(content, ep_num)
            workspace_manager.write_json(
                self.project_id, "40_scripts",
                f"chapter_{ep_num:02d}.summary.json",
                summary_data,
            )
